[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"

[tool.poetry]
name = "repo-to-md"
version = "0.1.1"
description = "Export Git repository contents to structured Markdown with AI chat integration"
authors = ["Georg Hildebrand <your-email@example.com>"]  # Add email
readme = "README.md"
license = "MIT"
homepage = "https://github.com/georghildebrand/Repo2Markdown"
repository = "https://github.com/georghildebrand/Repo2Markdown"
documentation = "https://github.com/georghildebrand/Repo2Markdown#readme"
keywords = ["markdown", "documentation", "git", "repository", "export", "ai-chat"]
classifiers = [
    "Development Status :: 4 - Beta",
    "Environment :: Console",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.11",
    "Programming Language :: Python :: 3.12",
    "Topic :: Documentation",
    "Topic :: Software Development :: Documentation",
    "Topic :: Text Processing :: Markup :: Markdown",
]
packages = [{include = "repo2md", from = "src"}]

[tool.poetry.dependencies]
python = "^3.11"
pyperclip = "^1.8.0"
twine = "^6.1.0"

[tool.poetry.group.dev.dependencies]
pytest = "^8.4"
pytest-cov = "^6.2"
black = "^25.1"
flake8 = "^7.3"
mypy = "^1.16.1"
types-pyperclip = "^1.9.0"

[tool.poetry.scripts]
repo2md = "repo2md.cli:main"

[tool.poetry.urls]
"Bug Tracker" = "https://github.com/georghildebrand/Repo2Markdown/issues"
"Changelog" = "https://github.com/georghildebrand/Repo2Markdown/releases"